### PR TITLE
Feature#26 create views for catalog

### PR DESCRIPTION
**Pull request by Jumaquba**
Changes in catalog view and customer

### CODE REVIEW

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Review by guillermo-delprado — DISMISSED** [review]
Lgtm 👍

**Review by lucasvidela94 — DISMISSED** [review]
Looks nice!Good job

**Review by HikingCarrot7 — DISMISSED** [review]
LGTM!

**Review by guillermo-delprado — APPROVED** [review]
👍

**Review by HikingCarrot7 — APPROVED** [review]
LGTM!

**Review by AgustinPalmaM — APPROVED** [review]
lgtm

**Pull request closed without merging**
