### PR TITLE
search by  fullname or dni

### PR DESCRIPTION
**Pull request by Jumaquba**
# Description
Search by name or dni

### CODE REVIEW

**Review by HikingCarrot7 — DISMISSED** [review]
LGTM!

**Review by lucasvidela94 — APPROVED** [review]
lgtm!

**Review by HikingCarrot7 — APPROVED** [review]
LGTM!

**Review by lucasvidela94 — APPROVED** [review]
Nice job guys!

**Review by guillermo-delprado — APPROVED** [review]
LGTM

**Pull request merged**
